[tool.poetry]
name = "backend-blender-control"
version = "0.1.0"
description = ""
authors = ["Alice Gowler <psyag8@exmail.nottingham.ac.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
